---

version: '3'

services:

  redis:
    image: redis
    volumes:
      - redis:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "make start"
    env_file:
      - .env
    volumes:
      - ~/.bash_history:/root/.bash_history
      - .:/root/hexlet-basics
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/tmp/hexletbasics:/var/tmp/hexletbasics
      - /tmp:/tmp
    depends_on:
      - solargraph

  # https://github.com/neoclide/coc-solargraph#configuration-options
  # external server
  solargraph:
    build: .
    command: "bundle exec solargraph socket --host=0.0.0.0 --port=7658"
    ports:
      - "7658:7658"
    env_file:
      - .env
    volumes:
      - ./:/root/hexlet-basics

  spring:
    build: .
    command: bin/spring server
    pid: host
    env_file:
      - .env
    volumes:
      - .:/root/hexlet-basics
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/root/hexlet-basics
      - /tmp:/tmp
      - /var/tmp/hexletbasics:/var/tmp/hexletbasics
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - spring
      - redis
      - web

  webpacker:
    build: .
    command: make webpacker
    ports:
      - "0.0.0.0:3035:3035"
    env_file:
      - .env
    volumes:
      - .:/root/hexlet-basics

  caddy:
    image: caddy:2.3.0
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  redis:
  caddy_data:
  caddy_config:
