---

version: '3'

services:

  redis:
    image: redis:6.2.7
    volumes:
      - redis:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "make start"
    env_file:
      - .env
    volumes:
      - ~/.bash_history:/root/.bash_history
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      # NOTE: контейнер с тестами моунтит /tmp с хоста, а не из локального волюма global_tmp
      - /tmp:/tmp
      - app_tmp:/app/tmp
    depends_on:
      - solargraph
      - spring
      - frontend

  # https://github.com/neoclide/coc-solargraph#configuration-options
  # external server
  solargraph:
    build: .
    command: "bundle exec solargraph socket --host=0.0.0.0 --port=7658"
    ports:
      - "7658:7658"
    env_file:
      - .env
    volumes:
      - .:/app
      - app_tmp:/app/tmp

  spring:
    build: .
    command: bin/spring server
    pid: host
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - app_tmp:/app/tmp
      - global_tmp:/tmp

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - app_tmp:/app/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - global_tmp:/tmp
    env_file:
      - .env
    depends_on:
      - spring
      - redis
      - web

  frontend:
    build: .
    command: make frontend
    # ports:
    #   - "3036:3036"
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - app_tmp:/app/tmp
      - .:/app

  webserver:
    image: caddy:2.6.2
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./public:/etc/caddy/public"
      - caddy_data:/data
      - caddy_config:/config
    # depends_on:
    #   - web

volumes:
  redis:
  caddy_data:
  caddy_config:
  app_tmp:
  global_tmp:
