---

hexlet_basics_mix_env: dev
hexlet_basics_run_user: "{{ ansible_ssh_user }}"
hexlet_basics_run_user_home: "{{ lookup('env','HOME') }}"
hexlet_basics_env_file: "{{ lookup('env','PWD') }}/.env"
hexlet_basics_node_env: development
hexlet_basics_app_host: "code-basics.test"
hexlet_basics_app_scheme: "https"
