---

apiVersion: batch/v1
kind: Job
metadata:
  name: exercises-css-job
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: pod-data
          emptyDir: {}
      initContainers:
        - name: exercises-css
          image: hexletbasics/exercises-css:latest
          command:
            - cp
            - "-r"
            - "/exercises-css/."
            - "/out"
          volumeMounts:
            - mountPath: /out
              name: pod-data
      containers:
        - name: app
          imagePullPolicy: Always
          image: hexletbasics/services-app:v271
          command:
            - mix
            - x.exercises.load
            - css
          volumeMounts:
            - mountPath: /hexletbasics/exercises-css
              name: pod-data
          resources:
            requests:
              cpu: 10m
          envFrom:
            - secretRef:
                name: hexlet-basics-secrets
            - secretRef:
                name: sparkpost-credentials
            - secretRef:
                name: github-credentials
            - configMapRef:
                name: hexlet-basics-config-map
