---

apiVersion: batch/v1
kind: Job
metadata:
  name: exercises-go-job
spec:

  template:
    spec:
      restartPolicy: Never

      volumes:
        - name: pod-data
          emptyDir: {}

      initContainers:
        - name: exercises-go
          image: hexletbasics/exercises-go
          command:
            - cp
            - "-r"
            - "/exercises-go/."
            - "/out"
          volumeMounts:
            - mountPath: /out
              name: pod-data

      containers:

        - name: app
          imagePullPolicy: Always
          image: hexletbasics/services-web:v271
          command:
            - mix
            - x.exercises.load
            - go
          volumeMounts:
            - mountPath: /hexletbasics/exercises-go
              name: pod-data
          resources:
            requests:
              cpu: 10m
          envFrom:
            - secretRef:
                name: hexlet-basics-secrets
            - secretRef:
                name: sparkpost-credentials
            - secretRef:
                name: github-credentials
            - configMapRef:
                name: hexlet-basics-config-map
