---

apiVersion: gwin.yandex.cloud/v1
kind: GatewayPolicy
metadata:
  name: "{{ include "codebasics.fullname" . }}-gateway-policy"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    {{- include "codebasics.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: "{{ include "codebasics.fullname" . }}-gateway"
  policy:
    subnets:
      {{- range .Values.gateway.subnets }}
      - "{{ . }}"
      {{- end }}
