---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{ include "codebasics.fullname" . }}-main-httproute"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    {{- include "codebasics.labels" . | nindent 4 }}
spec:
  hostnames:
    - "{{ .Values.gateway.hosts.primary }}"
    - "{{ .Values.gateway.hosts.wildcard }}"
  parentRefs:
    - name: "{{ include "codebasics.fullname" . }}-gateway"
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /ru/api/lessons/
      backendRefs:
        - name: "{{ include "codebasics.fullname" . }}-web-check-service"
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /api/lessons/
      backendRefs:
        - name: "{{ include "codebasics.fullname" . }}-web-check-service"
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: "{{ include "codebasics.fullname" . }}-web-service"
          port: 80
---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{ include "codebasics.fullname" . }}-secondary-httproute"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    {{- include "codebasics.labels" . | nindent 4 }}
spec:
  hostnames:
    - "{{ .Values.gateway.hosts.secondary }}"
  parentRefs:
    - name: "{{ include "codebasics.fullname" . }}-gateway"
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: "{{ include "codebasics.fullname" . }}-web-service"
          port: 80
