---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{ include "codebasics.fullname" . }}-redirect-httproute"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    {{- include "codebasics.labels" . | nindent 4 }}
spec:
  hostnames:
    - "{{ .Values.gateway.hosts.primary }}"
    - "{{ .Values.gateway.hosts.wildcard }}"
    - "{{ .Values.gateway.hosts.secondary }}"
  parentRefs:
    - name: "{{ include "codebasics.fullname" . }}-gateway"
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
