---

apiVersion: gwin.yandex.cloud/v1
kind: RoutePolicy
metadata:
  name: "{{ include "codebasics.fullname" . }}-route-policy"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    {{- include "codebasics.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "{{ include "codebasics.fullname" . }}-main-httproute"
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "{{ include "codebasics.fullname" . }}-secondary-httproute"
  policy:
    rules:
      http:
        upgradeTypes:
          - "{{ .Values.gateway.backend.upgradeTypes }}"
      backends:
        http:
          useHTTP2: {{ .Values.gateway.backend.useHttp2 }}
