apiVersion: v1
kind: Secret
metadata:
  name: "codebasics-environment-secrets"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codebasics.labels" . | nindent 4 }}
type: Opaque
{{- $secrets := get .Values "secrets" | default dict }}
{{- $codeBasics := get $secrets "codeBasics" | default dict }}
{{- $env := get $codeBasics "env" | default dict }}
{{- if gt (len $env) 0 }}
data:
  {{- range $key, $value := $env }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- else }}
data: {}
{{- end }}
