apiVersion: v1
kind: Secret
metadata:
  name: "docker-config"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codebasics.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  {{- $secrets := get .Values "secrets" | default dict }}
  {{- $docker := get $secrets "docker" | default dict }}
  .dockerconfigjson: {{ get $docker "config" | default "" | b64enc | quote }}
