---

apiVersion: gwin.yandex.cloud/v1
kind: ServicePolicy
metadata:
  name: "{{ .Release.Name }}-service-policy"
  namespace: "{{ .Release.Namespace }}"
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: "{{ .Release.Name }}-web-service"
    - group: ""
      kind: Service
      name: "{{ .Release.Name }}-web-check-service"
  policy:
    targets:
      type: Pod
