---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ .Release.Name }}-prepare-users-code-path-pod"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}-prepare-users-code-path-pod"
      app.kubernetes.io/instance: "{{ .Release.Name }}"

  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}-prepare-users-code-path-pod"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
        codebasics/pod: "{{ .Release.Name }}-prepare-users-code-path-pod"

    spec:
      nodeSelector:
        group: "{{ .Release.Namespace }}"

      volumes:
        - name: users-code-path
          hostPath:
            path: /tmp/hexlet-basics
            type: DirectoryOrCreate

      initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 1000:1000 /tmp/hexlet-basics']
          volumeMounts:
            - mountPath: /tmp/hexlet-basics
              name: users-code-path

      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10.1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
