{{- if .Values.autoscaling.web.enabled }}
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Release.Name }}-web-hpa"
  namespace: "{{ .Release.Namespace }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Release.Name }}-web-deployment"
  minReplicas: {{ .Values.autoscaling.web.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.web.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.web.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.web.targetMemoryUtilizationPercentage }}
{{- end }}
