---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ include "codebasics.fullname" . }}-prepare-users-code-path-pod"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    {{- include "codebasics.labels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "codebasics.fullname" . }}-prepare-users-code-path-pod"
      app.kubernetes.io/instance: "{{ .Release.Name }}"

  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "codebasics.fullname" . }}-prepare-users-code-path-pod"
        {{- include "codebasics.labels" . | nindent 8 }}
        codebasics/pod: "{{ include "codebasics.fullname" . }}-prepare-users-code-path-pod"

    spec:
      nodeSelector:
        group: "{{ .Release.Namespace }}"

      volumes:
        - name: users-code-path
          hostPath:
            path: /tmp/hexlet-basics
            type: DirectoryOrCreate

      initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 1000:1000 /tmp/hexlet-basics']
          volumeMounts:
            - mountPath: /tmp/hexlet-basics
              name: users-code-path

      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10.1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
