# Default values for hb-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: v817

replicaCount: 3

nginx:
  image:
    repository: hexletbasics/services-nginx
    pullPolicy: Always

web:
  image:
    repository: hexletbasics/services-app
    pullPolicy: Always

slack_notification: ['/app/deploy-notify.sh']

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
